# Generated by Django 2.0.6 on 2018-12-05 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181203_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_product',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
