# Generated by Django 2.0.6 on 2018-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181205_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.BooleanField(default=False),
        ),
    ]
