# Generated by Django 2.0.6 on 2018-12-04 06:05

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, default='')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='shop/thumbnail/')),
                ('content1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='shop/thumbnail/')),
                ('content2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='shop/thumbnail/')),
                ('content3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='shop/thumbnail/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
